knpu_oauth2_client:
    clients:

        # will create service: "knpu.oauth2.client.azure"
        # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\AzureClient
        # composer require thenetworg/oauth2-azure
        azure:
            # must be "azure" - it activates that type!
            type: azure
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(AZURE_ID)%'
            client_secret: '%env(AZURE_SECRET)%'
            # a route name you'll create
            redirect_route: connect_azure_check
            redirect_params: {}
            # Domain to build login URL
            # url_login: 'https://login.microsoftonline.com/'
            # Oauth path to authorize against
            # path_authorize: '/oauth2/authorize'
            # Oauth path to retrieve a token
            # path_token: '/oauth2/token'
            # Oauth scope send with the request
            # scope: {}
            # The tenant to use, default is `common`
            tenant: '%env(AZURE_TENANT)%'
            # Domain to build request URL
            # url_api: 'https://graph.windows.net/'
            # Oauth resource field
            # resource: null
            # The API version to run against
            api_version: '1.6'
            # Send resource field with auth-request
            # auth_with_resource: true
            # whether to check OAuth2 "state": defaults to true
            # use_state: true